let users=["Admin","Asad","Ali","Ejaz","Hussain"];
let user=users.pop();
console.log(user);
console.log(users);
let user1=users.pop();
console.log(user1);
console.log(users);
let user3=users.pop();
console.log(user3);
console.log(users);
let user4=users.pop();
console.log(user4);
console.log(users);
let user5=users.pop();
console.log(user5);
console.log(users);
